package detectors

import (
	"context"
	"regexp"
	"strings"
	"sync"

	"github.com/go-faker/faker/v4"
)

// EmailPseudonymizer maintains a bidirectional mapping between real and fake
// email addresses. Fake addresses are generated by go-faker and are stable
// within a session (same real address always maps to the same fake address).
type EmailPseudonymizer struct {
	mu         sync.RWMutex
	realToFake map[string]string
	fakeToReal map[string]string
}

func NewEmailPseudonymizer() *EmailPseudonymizer {
	return &EmailPseudonymizer{
		realToFake: make(map[string]string),
		fakeToReal: make(map[string]string),
	}
}

func (p *EmailPseudonymizer) GetOrCreate(real string) string {
	p.mu.RLock()
	if fake, ok := p.realToFake[real]; ok {
		p.mu.RUnlock()
		return fake
	}
	p.mu.RUnlock()

	p.mu.Lock()
	defer p.mu.Unlock()
	if fake, ok := p.realToFake[real]; ok {
		return fake
	}

	fake := faker.Email()
	// Ensure uniqueness: if the generated fake collides, keep regenerating.
	for _, exists := p.fakeToReal[fake]; exists; _, exists = p.fakeToReal[fake] {
		fake = faker.Email()
	}

	p.realToFake[real] = fake
	p.fakeToReal[fake] = real
	return fake
}

func (p *EmailPseudonymizer) Restore(fake string) (string, bool) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	real, ok := p.fakeToReal[fake]
	return real, ok
}

// EmailDetector detects email addresses and replaces them with stable fake
// addresses generated by go-faker, preserving the ability to unredact.
type EmailDetector struct {
	re            *regexp.Regexp
	pseudonymizer *EmailPseudonymizer
}

func NewEmailDetector() *EmailDetector {
	return &EmailDetector{
		// RFC 5321-ish pattern. The local part must start and end with an
		// alphanumeric character so that a hyphen immediately before the "@"
		// sign cannot be absorbed from surrounding punctuation (e.g. "foo-bar"
		// in "call foo-bar@example.com" must not match "bar@example.com" when
		// preceded by "foo-"). The domain part follows the same rule.
		re: regexp.MustCompile(
			`\b[a-zA-Z0-9][a-zA-Z0-9._%+\-]*@[a-zA-Z0-9][a-zA-Z0-9.\-]*\.[a-zA-Z]{2,}\b`,
		),
		pseudonymizer: NewEmailPseudonymizer(),
	}
}

func (d *EmailDetector) Type() string { return "email" }

// Redact replaces each detected email with a stable fake address and invokes
// callback for logging/stats.
func (d *EmailDetector) Redact(ctx context.Context, content string, callback RedactionCallback) string {
	return d.re.ReplaceAllStringFunc(content, func(match string) string {
		fake := d.pseudonymizer.GetOrCreate(match)
		callback(match, "email-address", "Email Address")
		return fake
	})
}

// Unredact replaces fake email addresses in content with the original real
// addresses. Only addresses that were substituted in the current session are
// restored.
func (d *EmailDetector) Unredact(content string) string {
	idxs := d.re.FindAllStringIndex(content, -1)
	if len(idxs) == 0 {
		return content
	}
	var b strings.Builder
	b.Grow(len(content))
	last := 0
	for _, loc := range idxs {
		start, end := loc[0], loc[1]
		b.WriteString(content[last:start])
		b.WriteString(d.unredactEmailMatch(content[start:end]))
		last = end
	}
	b.WriteString(content[last:])
	return b.String()
}

// unredactEmailMatch restores match when it equals a known fake. The regex can
// absorb a hyphenated prefix into the local part (e.g. "prefix-fake@dom.tld"
// when the real token was only "fake@dom.tld") because \b matches at the start
// of "prefix"; trim the local part from the left until Restore succeeds.
func (d *EmailDetector) unredactEmailMatch(match string) string {
	if real, ok := d.pseudonymizer.Restore(match); ok {
		return real
	}
	at := strings.IndexByte(match, '@')
	if at <= 0 {
		return match
	}
	for j := 1; j < at; j++ {
		sub := match[j:]
		if !d.re.MatchString(sub) {
			continue
		}
		if real, ok := d.pseudonymizer.Restore(sub); ok {
			return match[:j] + real
		}
	}
	return match
}
